language: java
dist: trusty
sudo: required
install: true

addons:
  chrome: stable
  
jdk:
- oraclejdk8

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  
install:
  - sudo apt-get install google-chrome-stable
  - wget -N https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/bin/
  - sudo chmod +x /usr/local/bin/chromedriver

script:
- mvn clean install

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'